# Generated by Django 6.0.3 on 2026-04-03 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('setor', models.CharField(blank=True, help_text='Setor/departamento do governo do Pará', max_length=100)),
                ('especializacao', models.CharField(blank=True, help_text='Especialização ou área de atuação', max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email_profissional', models.EmailField(blank=True, max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Técnico',
                'verbose_name_plural': 'Perfis de Técnicos',
                'ordering': ['usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAgricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.TextField()),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('documento_posse', models.FileField(blank=True, help_text='Comprovante de posse ou propriedade da terra', null=True, upload_to='documentos/')),
                ('nome_propriedade', models.CharField(max_length=255)),
                ('nomes_confrontantes', models.TextField(help_text='Nomes dos vizinhos/confrontantes separados por vírgula')),
                ('tamanho_total_ha', models.DecimalField(decimal_places=4, help_text='Tamanho total da área em hectares', max_digits=10)),
                ('tamanho_reserva_legal_ha', models.DecimalField(decimal_places=4, help_text='Tamanho da reserva legal em hectares', max_digits=10)),
                ('tamanho_app_ha', models.DecimalField(decimal_places=4, help_text='Tamanho da Área de Preservação Permanente em hectares', max_digits=10)),
                ('tamanho_area_uso_ha', models.DecimalField(decimal_places=4, help_text='Tamanho da área de uso em hectares', max_digits=10)),
                ('tamanho_area_consolidada_ha', models.DecimalField(decimal_places=4, help_text='Tamanho da área consolidada em hectares', max_digits=10)),
                ('numero_corpos_hidricos', models.PositiveIntegerField(default=0, help_text='Número de rios, igarapés e córregos')),
                ('numero_nascentes', models.PositiveIntegerField(default=0, help_text='Número de nascentes')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('observacoes_tecnico', models.TextField(blank=True, help_text='Observações do técnico sobre a validação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_agricultor', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agricultores_analisados', to='carpa.perfiltecnico')),
            ],
            options={
                'verbose_name': 'Perfil de Agricultor',
                'verbose_name_plural': 'Perfis de Agricultores',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
