# Generated by Django 6.0.3 on 2026-04-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilagricultor',
            name='acesso_propriedade',
            field=models.TextField(blank=True, help_text='Como chegar à propriedade: referências, estradas, ramais, distâncias'),
        ),
        migrations.AddField(
            model_name='perfilagricultor',
            name='cidade_propriedade',
            field=models.CharField(blank=True, help_text='Cidade onde a propriedade/posse está localizada (pode ser diferente da cidade de residência)', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilagricultor',
            name='foto_app',
            field=models.ImageField(blank=True, help_text='Foto da Área de Preservação Permanente (APP)', null=True, upload_to='fotos/app/'),
        ),
        migrations.AddField(
            model_name='perfilagricultor',
            name='foto_area_consolidada',
            field=models.ImageField(blank=True, help_text='Foto da Área Consolidada', null=True, upload_to='fotos/area_consolidada/'),
        ),
        migrations.AddField(
            model_name='perfilagricultor',
            name='foto_area_uso',
            field=models.ImageField(blank=True, help_text='Foto da Área de Uso', null=True, upload_to='fotos/area_uso/'),
        ),
        migrations.AddField(
            model_name='perfilagricultor',
            name='foto_corpos_hidricos',
            field=models.ImageField(blank=True, help_text='Foto dos Corpos Hídricos (rios, igarapés, córregos)', null=True, upload_to='fotos/corpos_hidricos/'),
        ),
        migrations.AddField(
            model_name='perfilagricultor',
            name='foto_nascentes',
            field=models.ImageField(blank=True, help_text='Foto das Nascentes', null=True, upload_to='fotos/nascentes/'),
        ),
        migrations.AddField(
            model_name='perfilagricultor',
            name='foto_reserva_legal',
            field=models.ImageField(blank=True, help_text='Foto da Reserva Legal (RL) — preferencialmente com coordenadas GPS', null=True, upload_to='fotos/reserva_legal/'),
        ),
        migrations.AlterField(
            model_name='perfilagricultor',
            name='tamanho_app_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfilagricultor',
            name='tamanho_area_consolidada_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfilagricultor',
            name='tamanho_area_uso_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfilagricultor',
            name='tamanho_reserva_legal_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfilagricultor',
            name='tamanho_total_ha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
