# Generated by Django 6.0.3 on 2026-04-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agriinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='CriarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='geospace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('docposse', models.BooleanField()),
                ('vizinhos', models.CharField()),
                ('Total_ha', models.FloatField()),
                ('property_name', models.CharField()),
                ('reservalegal_ha', models.FloatField()),
                ('app_ha', models.FloatField()),
                ('uso_ha', models.FloatField()),
                ('consolidada_ha', models.FloatField()),
                ('corposHidricos', models.IntegerField()),
                ('nascentes', models.IntegerField()),
            ],
        ),
    ]
